"""The main module of this package. It introduces the Reviewer class, which is responsible for fetching the files of a pull request, determining the relevant review points based on the content of the files, generating the input for the review process, and submitting the reviews to GitHub. The Reviewer class uses services from other modules to interact with GitHub, retrieve review points and examples from the database, and communicate with AI agents to generate the reviews."""

from typing import Any, final

from quality.agents import AGENTS
from quality.review.services.agent import AgentService
from quality.review.services.reporter import ReporterService
from quality.review.utils import create_suggestions_from_reviews, number_each_line
from quality.review_points.models.review_point import ReviewPoint
from quality.review.services.github import REVIEW_TYPE, GitHubService
from quality.review.services.example import get_raw_examples_by_review_point
from quality.review.services.topic import (
    get_review_points_by_topic,
    get_topic_by_builder_pattern,
)
from quality.review_points import REVIEW_POINTS_TOPIC


@final
class Reviewer:
    """
    A class representing a Nix code reviewer for a specific pull request.
    It fetches the PR files and evaluate the quality of the code based on predefined review points associated with the topics of the files in the PR.

    Attributes:
        - prnumber: The number of the pull request to review.
        - owner: The owner of the repository containing the pull request.
        - repo: The name of the repository containing the pull request.
        - harshness: An integer from 1 to 5 representing how harsh the review should
        - files: A dictionary mapping file names to their content for the files in the PR.
        - patches: A dictionary mapping file names to their patch for the files in the PR.
        - topics_by_file: A dictionary mapping file names to their associated review points topic.
        - review_points_by_file: A dictionary mapping file names to the list of review points associated    with their topic.
        - review_inputs: A dictionary mapping file names to the input that will be given to the agent for the review of the file. The input includes the content of the file and the instructions and examples for each review point associated with the file.
        - reviews: A dictionary mapping file names to the review generated by the agent for the file

    """

    def __init__(
        self,
        harshness: int = 5,
    ):
        self.prnumber: int = 0
        self.owner: str = ""
        self.repo: str = ""
        self.harshness = harshness
        self.files = {}
        self.patches = {}
        self.topics_by_file = {}
        self.review_points_by_file = {}
        self.review_inputs = {}
        self.reviews: dict[str, list[dict[str, str | int]]] = {}

    def __generate_topics(
        self, files: dict[str, str]
    ) -> dict[str, REVIEW_POINTS_TOPIC]:
        """
        Private method to generate topics for all the files in a PR. If a file doesn't match any topic, it is not included in the returned dictionary, and thus not reviewed.
        """
        topics_by_file: dict[str, REVIEW_POINTS_TOPIC] = {}
        for file_name, file_content in files.items():
            topic: REVIEW_POINTS_TOPIC | None = get_topic_by_builder_pattern(
                file_content
            )
            if topic is not None:
                topics_by_file[str(file_name)] = topic
        return topics_by_file

    def __generate_review_points(
        self, topics_by_file: dict[str, REVIEW_POINTS_TOPIC]
    ) -> dict[str, list[ReviewPoint]]:
        """
        Private method to generate review points for all the files in a PR based on their topics.
        """
        return {
            file_name: get_review_points_by_topic(topic)
            for file_name, topic in topics_by_file.items()
        }

    def __generate_final_input(
        self, review_points_by_file: dict[str, list[ReviewPoint]]
    ) -> dict[str, Any]:
        """
        Private method to generate the final input for the review.
        For each file, it creates a dictionary mapping each review point to its instruction and examples.
        """
        return {
            file_name: {
                "content": number_each_line(self.files[file_name]),
                "review_points": {
                    str(review_point.review_point_name): {
                        "instructions": str(review_point.instructions),
                        "examples": get_raw_examples_by_review_point(review_point),
                    }
                    for review_point in review_points
                },
            }
            for file_name, review_points in review_points_by_file.items()
        }

    def checkout_pr(
        self,
        prnumber: int,
        owner: str = "NixOS",
        repo: str = "nixpkgs",
        env_var_name: str = "ACCESS_TOKEN",
    ) -> None:
        """Fetches the PR files and patches, generates the topics, review points and final input for the review process."""
        # Set PR information of the reviewer
        self.prnumber = prnumber
        self.owner = owner
        self.repo = repo

        # Fetch PR files and patches
        github_service = GitHubService(env_var_name=env_var_name)
        self.files, self.patches = github_service.get_pr_files(
            prnumber=prnumber, owner=owner, repo=repo
        )

        # Generate topics, review points and final input for the review process
        self.topics_by_file = self.__generate_topics(self.files)
        self.review_points_by_file = self.__generate_review_points(self.topics_by_file)
        self.review_inputs = self.__generate_final_input(self.review_points_by_file)

    def review_files(self, agent: AGENTS, model: str) -> None:
        """Reviews the files in the PR using the specified agent and model, and stores the reviews in the reviews attribute."""
        if not self.review_inputs or self.review_inputs == {}:
            raise ValueError("No files to review.")

        agent_service = AgentService(agent, model)
        for file_name, review_input in self.review_inputs.items():
            print(f"Reviewing file: {file_name}")
            rep = agent_service.ask_agent_for_review(review_input)
            self.reviews[file_name] = rep["changes"]

    def submit_reviews(
        self,
        review_message: str = "",
        additional_review_message: str = "",
        review_type: REVIEW_TYPE = REVIEW_TYPE.COMMENT,
    ) -> None:
        """Submits the reviews to GitHub as a review on the PR."""
        if not self.reviews or self.reviews == {}:
            raise ValueError("No reviews to submit.")

        if review_message == "":
            with open("quality/review/messages/default_review_message.md", "r") as f:
                review_message = f.read()
            if additional_review_message != "":
                review_message = (
                    additional_review_message + "\n --- \n" + review_message
                )

        print(f"Submitting review of PR {self.owner}/{self.repo}#{self.prnumber}")
        github_service = GitHubService()
        github_service.submit_review(
            self.prnumber,
            review_message,
            reviews=self.reviews,
            owner=self.owner,
            repo=self.repo,
            review_type=review_type,
        )
        print("Review submitted successfully.")

    def print_reviews(self) -> None:
        reporter = ReporterService()
        formatted_reviews = create_suggestions_from_reviews(self.reviews)
        reporter.produce_report_from_formatted_reviews(formatted_reviews)
        reporter.print_report()

    def save_reviews(self, path: str) -> None:
        if not self.reviews or self.reviews == {}:
            raise ValueError("No reviews to format.")
        if path == "":
            print("No path provided for saving the report. Using default path.")
            path = f"review_report_{self.owner}_{self.repo}_{self.prnumber}.md"
        reporter = ReporterService()
        formatted_reviews = create_suggestions_from_reviews(self.reviews)
        reporter.produce_report_from_formatted_reviews(formatted_reviews)
        _ = reporter.save_report(path)


if __name__ == "__main__":
    reviewer = Reviewer(harshness=5)
    reviewer.checkout_pr(prnumber=474854)
    print(reviewer.review_inputs)
