"""Utility functions for processing file content and generating suggestions from reviews."""

from typing import Any


def number_each_line(file: str) -> str:
    """Takes a string representing the content of a file and returns a new string where each line is prefixed with its line number, starting from 1. The line number is followed by a colon and a space before the original line content. This aims to help the LLM to reference specific lines in the file when generating suggestions for code changes."""
    lines = file.splitlines()
    return "\n".join(f"{i + 1}: {line}" for i, line in enumerate(lines))


def create_suggestions_from_reviews(reviews: dict[str, Any]) -> list[dict[str, str]]:
    """Converts the reviews generated by the reviewer into a format suitable for posting as suggestions on GitHub. Each suggestion includes the file path, line number, side (LEFT or RIGHT), and the body of the suggestion, which contains the explanation and the suggested code change formatted as a markdown code block."""
    return [
        {
            "path": file_path,
            "line": change["line_number"],
            "side": "RIGHT",  # Referring to the new code in the PR
            "body": (
                f"{change['explanation']}\n\n"
                f"```suggestion\n"
                f"{change['after']}\n"
                f"```"
            ),
        }
        for file_path, changes in reviews.items()
        for change in changes
    ]
