name: Pytest lite

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  TestingLite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install uv
      - name: Test with pytest
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          uv run --dev pytest tests/ --ignore=tests/test_review_reviewer.py --ignore=tests/test_review_service_agent.py -v
